### ISSUE TITLE
Cannot install Finance::OFX through CPAN clients.

### ISSUE THREAD

**Issue by ioanrogers** [bfoz/p5-Finance-OFX#2]
Hi,

First, thanks for the module, it saves me from some monthly accounting tedium!

The problem: I'm unable to install Finance::OFX through the cpan client:

```
Running install for module 'Finance::OFX'

  The module Finance::OFX isn't available on CPAN.

  Either the module has not yet been uploaded to CPAN, or it is
  temporary unavailable. Please contact the author to find out
  more about the status. Try 'i Finance::OFX'.
```

It's also not possible to find the dist on metacpan: CPAN-API/metacpan-web#537

I found that the tarball was uploaded under `/authors/id/B/BF/BFOZ/bfoz/` (username duplicated), so hopefully just re-uploading to PAUSE with the correct path will fix things.

**Comment by bfoz** [comment]
This is a recurring problem. Myself, and several others, have looked into it before without finding a root cause. Eventually the module comes back and everything is copasetic. Any idea how long the problem has persisted this time?

I'll try uploading a new version as soon as I have time to look into it. Unfortunately I haven't looked at this code is some time, so it'll take me awhile to get back into it.

**Comment by ioanrogers** [comment]
At least five months, from that metacpan issue. If the subdir _is_ what's causing the problem, its mtime is Sep 2011, so maybe a year.

What method are you using to upload to PAUSE?

Is there any online archive of the previous issues?

**Comment by bfoz** [comment]
I've uploaded the file to PAUSE again and it's showing up in my files list without that errant subdirectory. We'll see what happens after the indexer is finished with it.

I seem to remember that adding that subdirectory was the recommended solution the last time the module mysteriously disappeared. But I don't remember why.

**Comment by ioanrogers** [comment]
Yup, seems fixed! Thanks
